#! /bin/sh -x

die(){ echo >&2 "!! $*"; exit 1; }

test -z "$1" && die "ARG1 needs to be VIRSH connection string"
test -z "$RESALLOC_NAME" && die "no vm specified, empty \$RESALLOC_NAME variable"

virsh -c "$1" destroy  "$RESALLOC_NAME"
virsh -c "$1" undefine "$RESALLOC_NAME" --remove-all-storage --nvram
