#! /bin/sh -x

set -e

src_img=$1
dst_img=/tmp/newdisk.qcow2

cp "$src_img" "$dst_img"

# We could be using 'virt-resize --expand /dev/sda2' instead, but we are running
# too old hypervisor to handle Fedora images:
#       e2fsck: Get a newer version of e2fsck!
# So we use cloud-utils-growpart instead.

guestfish -a "$dst_img" <<EOF
run
mount /dev/sda2 /
write        /etc/rc.d/rc.local "#! /bin/sh\n"
write-append /etc/rc.d/rc.local "set -e\n"
write-append /etc/rc.d/rc.local "mkdir -p /config\n"
write-append /etc/rc.d/rc.local "mount /dev/disk/by-label/copr_config /config\n"
write-append /etc/rc.d/rc.local "sh -x /config/pre-network-script.sh\n"
chmod 0755   /etc/rc.d/rc.local
EOF

virt-customize -a "$dst_img" \
    --install cloud-utils-growpart \
    --install cloud-utils \
    --install qemu-guest-agent \
    --root-password password:redhat  \
    --selinux-relabel \
    --uninstall cloud-init
