#! /bin/sh -x

set -e

src_img=$1
dst_img=/tmp/newdisk.qcow2

cp "$src_img" "$dst_img"

# We could be using 'virt-resize --expand /dev/sda2' instead, but we are
# running too old hypervisor to handle Fedora images:
# e2fsck: Get a newer version of e2fsck!
# (his requires cloud-utils-growpart installed)
# qemu-img resize "$dst_img" 9G

guestfish -a "$dst_img" <<EOF
run
mount /dev/sda2 /
write        /etc/rc.d/rc.local "#! /bin/sh\n"
write-append /etc/rc.d/rc.local "set -e\n"
write-append /etc/rc.d/rc.local "mkdir -p /config\n"
write-append /etc/rc.d/rc.local "mount /dev/disk/by-label/copr_config /config\n"
write-append /etc/rc.d/rc.local "sh -x /config/pre-network-script.sh\n"
write-append /etc/rc.d/rc.local "mkswap /dev/vdc && swapon /dev/vdc\n"
chmod 0755   /etc/rc.d/rc.local
EOF

install_packages='
    cloud-utils
    cloud-utils-growpart
    copr-builder
    qemu-guest-agent
    htop
    vim
'

virt-customize -a "$dst_img" \
    --update \
    --install "$(echo $install_packages | tr ' ' ,)" \
    --uninstall cloud-init \
    --selinux-relabel
