- name: provision builder
  hosts: all
  gather_facts: False
  remote_user: root

  vars_files:
    - nova_cloud_vars.yml
  vars:
    prepare_base_image: False

  tasks:
  - include: "provision_builder_tasks.yml"
